---
all:
  children:
    NETWORK:
      children:
        ISP_ROUTERS:
          hosts:
            isp-router-1:
              ansible_host: 172.100.100.2
            isp-router-2:
              ansible_host: 172.100.100.3
        EDGE_ROUTERS:
          hosts:
            edge-router-1:
              ansible_host: 172.100.100.4
            edge-router-2:
              ansible_host: 172.100.100.5
        CORE:
          hosts:
            core-router-1:
              ansible_host: 172.100.100.6
