---
hostname: edge-router-2

loopback_interfaces:
  - name: Loopback0
    ip_address: 192.168.10.2/32

ethernet_interfaces:
  - name: Ethernet1
    ip_address: 10.0.1.6/30
    peer: isp-router-1
    peer_interface: Ethernet2
    description: To ISP1
  - name: Ethernet2
    ip_address: 10.0.2.6/30
    peer: isp-router-2
    peer_interface: Ethernet2
    description: To ISP2
  - name: Ethernet3
    ip_address: 10.0.3.2/30
    peer: edge-router-1
    peer_interface: Ethernet3
    description: To edge-router-1 (iBGP)
  - name: Ethernet4
    ip_address: 10.0.4.5/30
    peer: core-router-1
    peer_interface: Ethernet2
    description: To core-router-1

router_bgp:
  as: "65000"
  router_id: 192.168.10.2
  peer_groups:
    - name: ISP1
      remote_as: "64501"
    - name: ISP2
      remote_as: "64502"
    - name: EDGE-IBGP
      remote_as: "65000"
      next_hop_self: true
    - name: CORE
      remote_as: "65001"
  neighbors:
    - ip_address: 10.0.1.5
      peer_group: ISP1
      description: isp-router-1
    - ip_address: 10.0.2.5
      peer_group: ISP2
      description: isp-router-2
    - ip_address: 10.0.3.1
      peer_group: EDGE-IBGP
      description: edge-router-1
    - ip_address: 10.0.4.6
      peer_group: CORE
      description: core-router-1
  address_family_ipv4:
    peer_groups:
      - name: ISP1
        activate: true
        route_map_in: ISP-IN
        route_map_out: ISP-OUT
      - name: EDGE-IBGP
        activate: true
      - name: CORE
        activate: true
        
route_maps:
  - name: ISP-IN
    sequence_numbers:
      - sequence: 10
        type: permit
        match:
          - ip address prefix-list DEFAULT-ONLY
        set:
          - set local-preference 50
  - name: ISP-OUT
    sequence_numbers:
      - sequence: 10
        type: permit
        match:
          - ip address prefix-list EXTERNAL-NET
        set:
          - as-path prepend 65000 65000 65000

event_handlers:
  - name: ISP1-DOWN
    trigger: on-logging
    trigger_on_logging:
      regex: "CONNECTIVITYMON-5-HOST_UNREACHABLE.*INTERNET.*from interface Vlan111.*"
    delay: 0
    actions:
      bash_command: |
        FastCli -p 15 -c $'configure
        route-map ISP-IN permit 10
        set local-preference 200
        route-map ISP-OUT permit 10
        no set as-path prepend 65000 65000 65000
        !
        clear bgp peer-group ISP1 soft in'
        
  - name: ISP1-UP
    trigger: on-logging
    trigger_on_logging:
      regex: "CONNECTIVITYMON-5-HOST_REACHABLE.*INTERNET.*from interface Vlan111.*"
    delay: 5
    actions:
      bash_command: |
        FastCli -p 15 -c $'configure
        route-map ISP-IN permit 10
        set local-preference 50
        route-map ISP-OUT permit 10
        set as-path prepend 65000 65000 65000
        !
        clear bgp peer-group ISP1 soft in'
